name: Trigger auto deployment for container-app-2o2daflphhqz2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-2o2daflphhqz2-AutoDeployTrigger-2e6b5c2a-efb6-42fe-8f20-f88c18375b53.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP2O2DAFLPHHQZ2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP2O2DAFLPHHQZ2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP2O2DAFLPHHQZ2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP2O2DAFLPHHQZ2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP2O2DAFLPHHQZ2_REGISTRY_PASSWORD }}
          containerAppName: container-app-2o2daflphhqz2
          resourceGroup: appspacesfastapi86fb
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


